apiVersion: v1
kind: ConfigMap
metadata:
  name: pronunt-config-service-config
  namespace: prism
data:
  APP_NAME: pronunt-config-service
  APP_ENV: production
  APP_HOST: 0.0.0.0
  APP_PORT: "8000"
  LOG_LEVEL: INFO

